// <auto-generated />
namespace CaloriesPlan.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPagingToProcedure_sp_GetUserMeals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPagingToProcedure_sp_GetUserMeals));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251850482_AddPagingToProcedure_sp_GetUserMeals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
